---

resource_types:

# Send notifications to the Telegram
- name: telegram-notification
  type: docker-image
  source:
    repository: w32blaster/concourse-telegram-notifier
    tag: latest


resources:

- name: after-midnight
  type: time
  source:
    start: 1:00 AM
    stop: 2:00 AM
    days: [Monday, Friday]

- name: telegram-notification
  type: telegram-notification
  source:
    bot_token: ((bot-token))

jobs:
- name: "HSL parse"
  public: true
  plan:

  - get: after-midnight
    trigger: true  

  # Build
  - task: "Download and parse HSL data"
    params:
      HSL_FTP_HOSTNAME: ((ftp-hostname))
      HSL_FTP_USERNAME: ((ftp-user))
      HSL_FTP_PASSWORD: ((ftp-password))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: "w32blaster/hsl-gtfs-parser", tag: "latest" }
      
      run:
        path: /root/build.sh  

    on_failure:
      put: telegram-notification
      params:
        chat_id: ((chat-id))
        text: " 🔴 Achtung! HSL file uploading was failed! [Build $BUILD_NAME](http://ci.daxi.meibe.eu:8080/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)"

  # Send message to Telegram that everything is fine
  - put: telegram-notification
    params:
      chat_id: ((chat-id))
      text: "✅ HSL db file was updated and deployed to the server"

